# Generated by Django 5.1 on 2024-08-23 05:15

import amazon.models # type: ignore
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=amazon.models.filename)),
                ('Description', models.TextField(max_length=700)),
                ('Status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Vendor', models.CharField(max_length=150)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to=amazon.models.filename)),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('Description', models.TextField(max_length=700)),
                ('Status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('Trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.price')),
            ],
        ),
    ]
