# Generated by Django 5.1 on 2024-08-26 12:34

import amazon.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_rename_name_price_name_rename_name_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=amazon.models.filename)),
                ('Description', models.TextField(max_length=700)),
                ('Status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.customer'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
