# Generated by Django 5.1 on 2024-08-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_rename_price_product_customer_alter_customer_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_image',
            new_name='product_images',
        ),
    ]
