# Generated by Django 5.1 on 2024-08-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_rename_product_image_product_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_images',
            new_name='product_image',
        ),
    ]
